
from FXPy import *


#  Generated from file folder0a.gif
folder0a = "47 49 46 38 39 61 20 00 20 00 f2 06 00 00 00 00 \
  00 00 99 00 00 ff 99 99 99 c8 b4 c8 cc cc cc ff \
  ff ff c8 b4 c8 21 f9 04 01 00 00 07 00 21 fe 4e \
  54 68 65 20 49 63 6f 6e 6f 6c 6f 67 20 3a 20 54 \
  68 65 20 41 72 74 20 6f 66 20 56 69 72 74 75 61 \
  6c 20 4c 69 74 74 65 72 0a 20 20 20 68 74 74 70 \
  3a 2f 2f 77 77 77 2e 6f 7a 65 6d 61 69 6c 2e 63 \
  6f 6d 2e 61 75 2f 7e 61 66 61 63 74 6f 72 00 2c \
  00 00 00 00 20 00 20 00 c2 00 00 00 00 00 99 00 \
  00 ff 99 99 99 c8 b4 c8 cc cc cc ff ff ff c8 b4 \
  c8 03 bb 78 ba 2c ce f0 84 19 5b 15 95 ca 7a 9c \
  00 85 11 86 40 69 96 53 a0 a8 5b 05 8a c0 20 cf \
  74 3d 00 9c 82 e9 cf ce a9 2c 8e cf f3 60 b0 28 \
  c1 20 e3 35 82 9d 9e 50 5c 24 4a 35 e5 2e c5 4e \
  4e a3 84 78 bc db ee a5 f1 35 1e 53 5d 22 e6 f4 \
  3b b6 de cb a6 5c 44 27 ad ae 07 26 cc c6 9f 49 \
  a7 05 31 7d 7c 7f 78 86 87 39 5f 3e 11 5c 89 59 \
  65 3f 70 11 18 90 8b 8c 62 60 93 6d 92 9a 9d 66 \
  0b 98 16 3c 90 2b 6e 40 69 a4 a4 77 12 40 a0 0b \
  6a 7a 85 a0 4a 49 2e 75 b7 73 05 68 1a b6 b9 b7 \
  68 ab 39 00 b8 82 83 35 b2 0a c3 23 c5 c6 7e c2 \
  7b cd 34 c8 10 25 d1 d2 88 d8 d9 da 78 09 00 3b"



# Generated by from file compress0c.gif
compress0c = "47 49 46 38 39 61 20 00 20 00 f2 06 00 00 00 00 \
  33 99 99 00 ff ff 99 99 99 c8 b4 c8 cc cc cc ff \
  ff ff c8 b4 c8 21 f9 04 01 00 00 07 00 21 fe 4e \
  54 68 65 20 49 63 6f 6e 6f 6c 6f 67 20 3a 20 54 \
  68 65 20 41 72 74 20 6f 66 20 56 69 72 74 75 61 \
  6c 20 4c 69 74 74 65 72 0a 20 20 20 68 74 74 70 \
  3a 2f 2f 77 77 77 2e 6f 7a 65 6d 61 69 6c 2e 63 \
  6f 6d 2e 61 75 2f 7e 61 66 61 63 74 6f 72 00 2c \
  00 00 00 00 20 00 20 00 c2 00 00 00 33 99 99 00 \
  ff ff 99 99 99 c8 b4 c8 cc cc cc ff ff ff c8 b4 \
  c8 03 b4 78 ba dc 0e 10 ba 49 17 34 05 e3 02 2a \
  08 60 28 06 9d 12 49 14 60 08 6b cb be 46 79 46 \
  55 3d cd 36 20 ec 7c 2f 94 07 5c 6a 44 04 9a 4e \
  a9 82 72 c9 6c 72 66 28 db 6d d6 14 06 9d d8 25 \
  34 ca 50 c1 be ab df 71 7b 73 99 59 c6 20 72 48 \
  14 a5 ad ec 36 08 08 97 7a 0a 03 bc 3e 6d 9f d2 \
  fa 0f 74 1a 4a 32 7c 35 51 00 7a 79 85 5d 5b 8e \
  0b 79 03 1e 8e 8e 4f 50 81 94 7f 57 91 7b 53 72 \
  6e 0c 8b 39 3e a4 69 78 86 5d 9f 73 0d a2 87 a4 \
  3e a6 03 a8 41 67 66 86 ad 1e aa 24 0d a7 a3 af \
  b0 90 1c 87 99 7f 2a 19 c7 c2 0d c4 50 96 75 63 \
  cb 28 bd 80 52 ce 09 00 3b"


# Main Window
class ShutterWindow(FXMainWindow):

# Construct an application
    def __init__(self, app):
        super().__init__(app, "Shutter Widget Test", None, None, DECOR_ALL,0,0,600,600)

        icon = bytes.fromhex(folder0a)

        foldericon = FXGIFIcon(app,icon)
        icon = bytes.fromhex(compress0c)
        compressicon = FXGIFIcon(app,icon)

        contents = FXHorizontalFrame(self,LAYOUT_FILL_X|LAYOUT_FILL_Y)
        listFrame = FXVerticalFrame(contents,LAYOUT_FILL_X|LAYOUT_FILL_Y|LAYOUT_TOP|LAYOUT_LEFT,0,0,0,0,10,10,10,10)
        FXLabel(listFrame, "Tree List",None,JUSTIFY_CENTER_X|LAYOUT_FILL_X)
        FXHorizontalSeparator(listFrame,SEPARATOR_GROOVE|LAYOUT_FILL_X)
        tree = FXTreeList(listFrame,None,0,FRAME_SUNKEN|FRAME_THICK|LAYOUT_FILL_X|LAYOUT_FILL_Y|LAYOUT_TOP|LAYOUT_RIGHT|TREELIST_SHOWS_LINES|TREELIST_SHOWS_BOXES)

        buttonFrame = FXVerticalFrame(contents,FRAME_RAISED|LAYOUT_FILL_Y|LAYOUT_TOP|LAYOUT_LEFT,0,0,0,0,10,10,10,10)
        FXLabel(buttonFrame,"Button Frame",None,JUSTIFY_CENTER_X|LAYOUT_FILL_X)
        FXHorizontalSeparator(buttonFrame,SEPARATOR_RIDGE|LAYOUT_FILL_X)

        shutterFrame = FXShutter(buttonFrame,None,0,FRAME_SUNKEN|LAYOUT_FILL_Y|LAYOUT_FILL_X|LAYOUT_TOP|LAYOUT_LEFT,0,0,0,0,0,0,0,0,0,0)
        shutterItem = FXShutterItem(shutterFrame,"Test 1",None,LAYOUT_FILL_X|LAYOUT_FILL_Y|LAYOUT_TOP|LAYOUT_LEFT,0,0,0,0,10,10,10,10,10,10)
        FXButton(shutterItem.getContent(),FXString.null,foldericon,app,FXApp.ID_QUIT,FRAME_THICK|FRAME_RAISED|LAYOUT_FILL_X|LAYOUT_TOP|LAYOUT_LEFT,0,0,0,0,10,10,5,5)
        FXButton(shutterItem.getContent(),FXString.null,compressicon,app,FXApp.ID_QUIT,FRAME_THICK|FRAME_RAISED|LAYOUT_FILL_X|LAYOUT_TOP|LAYOUT_LEFT,0,0,0,0,10,10,5,5)
        FXButton(shutterItem.getContent(),FXString.null,compressicon,app,FXApp.ID_QUIT,FRAME_THICK|FRAME_RAISED|LAYOUT_FILL_X|LAYOUT_TOP|LAYOUT_LEFT,0,0,0,0,10,10,5,5)
        FXButton(shutterItem.getContent(),FXString.null,foldericon,app,FXApp.ID_QUIT,FRAME_THICK|FRAME_RAISED|LAYOUT_FILL_X|LAYOUT_TOP|LAYOUT_LEFT,0,0,0,0,10,10,5,5)

        shutterItem = FXShutterItem(shutterFrame,"Test 2",None,LAYOUT_FILL_X|LAYOUT_TOP|LAYOUT_LEFT,0,0,0,0,10,10,10,10,10,10)
        FXButton(shutterItem.getContent(),FXString.null,foldericon,app,FXApp.ID_QUIT,FRAME_THICK|FRAME_RAISED|LAYOUT_FILL_X|LAYOUT_TOP|LAYOUT_LEFT,0,0,0,0,10,10,5,5)
        FXButton(shutterItem.getContent(),FXString.null,compressicon,app,FXApp.ID_QUIT,FRAME_THICK|FRAME_RAISED|LAYOUT_FILL_X|LAYOUT_TOP|LAYOUT_LEFT,0,0,0,0,10,10,5,5)
        FXButton(shutterItem.getContent(),FXString.null,foldericon,app,FXApp.ID_QUIT,FRAME_THICK|FRAME_RAISED|LAYOUT_FILL_X|LAYOUT_TOP|LAYOUT_LEFT,0,0,0,0,10,10,5,5)

        shutterItem = FXShutterItem(shutterFrame,"Test 3",None,LAYOUT_FILL_X|LAYOUT_TOP|LAYOUT_LEFT,0,0,0,0,10,10,10,10,10,10)
        FXButton(shutterItem.getContent(),FXString.null,foldericon,app,FXApp.ID_QUIT,FRAME_THICK|FRAME_RAISED|LAYOUT_FILL_X|LAYOUT_TOP|LAYOUT_LEFT,0,0,0,0,10,10,5,5)
        FXButton(shutterItem.getContent(),FXString.null,compressicon,app,FXApp.ID_QUIT,FRAME_THICK|FRAME_RAISED|LAYOUT_FILL_X|LAYOUT_TOP|LAYOUT_LEFT,0,0,0,0,10,10,5,5)

        shutterItem = FXShutterItem(shutterFrame,"Test 4",None,LAYOUT_FILL_X|LAYOUT_TOP|LAYOUT_LEFT,0,0,0,0,10,10,10,10,10,10)
        FXButton(shutterItem.getContent(),FXString.null,compressicon,app,FXApp.ID_QUIT,FRAME_THICK|FRAME_RAISED|LAYOUT_FILL_X|LAYOUT_TOP|LAYOUT_LEFT,0,0,0,0,10,10,5,5)


# Here we begin
# Make application
application = FXApp("Shutter","FXPyTest")

win = ShutterWindow(application)

# Create the application's windows
application.create()

win.show()

# Run the application
application.run()
